### ISSUE TITLE
Spotify: Authentication error (Could not login)

### ISSUE THREAD

**Issue by foreignmeloman** [vhaudiquet/BladePlayer#26]
As the title says - I cant login. The credentials are correct. Tried both with email and username.

**Comment by foreignmeloman** [comment]
@vhaudiquet thanks for a quick response!

Phone model: OnePlus 7T
OS: OxygenOS 12 (Based on Android 12)

I've uninstalled the Spotify app an the login flow worked.

Although now the UI is a bit confusing because I can't find my playlists or anything from my library.

**Comment by TomBonnot** [comment]
I had the same problem. Since I am using Rethink DNS through AdGuardDNS, I don't know why but the Spotify Auth doesn't like DNS at all (even if I unblock everything), so just bypass the app for the DNS and everything is fine.

**Comment by vhaudiquet** [comment]
This is weird because i'm using CloudFlare DNS with PiHole through Wireguard myself and i have no issue...

Anyway if the issue comes from Spotify Auth lib, which maybe it is, i'm afraid i won't be able to do anything...

I will try to keep looking and if i'm able to replicate your issue or find something about it, i'll keep you posted :)

**Comment by primski** [comment]
Since latest spotify update, i get Authentication error too now. Tried it with spotify app installed and not installed.  I don't think its a dns issue since i tried it both on wifi and data connection. did spotify break this? thanks.
