### ISSUE TITLE
Cache size limitation settings

### ISSUE THREAD

**Issue by siggi1984** [vhaudiquet/BladePlayer#29]
Hello, I have a question.

I have observed that the more songs I play, the larger the cache memory.

What is stored in the cache? Are there perhaps the songs for later playback cached or what is stored there between?

**Comment by vhaudiquet** [comment]
Yes ! The cache is mostly used to store the songs that you play.
The way it works is while you are playing the beginning of the song, the end gets cached, basically.

I just never delete the cache because i think that most phones out there have huge storage but maybe not so huge data plans, and playing back the songs from cache does not require any data, so to me it is a win.

If you are worried about the cache taking up too much space, i could add an option to delete cache in Blade, or to auto-delete oldest entries when the cache is bigger than a certain limit ?

**Comment by siggi1984** [comment]
Okay my English is mega bad and I use a translator.

Do I understand correctly that if I play a song once it will be cached and if I play the same song again it will be played from the cache and will not consume any data volume?

A way to limit the cache would be great. There should be an option in the settings to set the cache size to 2,4,6,8,...

**Comment by vhaudiquet** [comment]
Yes, you are right

Yes, i think it will be easy to implement, and it would indeed be a great option

**Comment by siggi1984** [comment]
There's nothing going on here.

**Comment by siggi1984** [comment]
There's nothing going on here.
